root = "."
tmp_dir = "tmp"

[build]
  bin = "tmp/main"
  full_bin = "./tmp/main"
  cmd = "go build -o tmp/main ./cmd/server"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_regex = ["_test\\.go"]

[log]
  time = true

[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  runner = "magenta"

[screen]
  clear_on_build = true
